// This file is auto-generated by @hey-api/openapi-ts

export const Body_charters_create_charterSchema = {
    properties: {
        charter_base: {
            '$ref': '#/components/schemas/CharterBase'
        },
        banner_image: {
            type: 'string',
            format: 'binary',
            title: 'Banner Image'
        },
        block_1_image: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Block 1 Image'
        },
        block_2_image: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Block 2 Image'
        }
    },
    type: 'object',
    required: ['charter_base', 'banner_image'],
    title: 'Body_charters-create_charter'
} as const;

export const Body_charters_update_charterSchema = {
    properties: {
        charter_base: {
            '$ref': '#/components/schemas/CharterUpdateBase'
        },
        banner_image: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Banner Image'
        },
        block_1_image: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Block 1 Image'
        },
        block_2_image: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Block 2 Image'
        }
    },
    type: 'object',
    required: ['charter_base'],
    title: 'Body_charters-update_charter'
} as const;

export const Body_crew_members_create_crew_memberSchema = {
    properties: {
        crew_member_base: {
            '$ref': '#/components/schemas/CrewMemberBase'
        },
        image: {
            type: 'string',
            format: 'binary',
            title: 'Image'
        }
    },
    type: 'object',
    required: ['crew_member_base', 'image'],
    title: 'Body_crew members-create_crew_member'
} as const;

export const Body_crew_members_update_crew_memberSchema = {
    properties: {
        crew_member_base: {
            '$ref': '#/components/schemas/CrewMemberUpdateBase'
        },
        image: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        }
    },
    type: 'object',
    required: ['crew_member_base'],
    title: 'Body_crew members-update_crew_member'
} as const;

export const Body_destinations_create_destinationSchema = {
    properties: {
        destination_base: {
            '$ref': '#/components/schemas/DestinationBase'
        },
        banner_image: {
            type: 'string',
            format: 'binary',
            title: 'Banner Image'
        },
        side_image: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Side Image'
        }
    },
    type: 'object',
    required: ['destination_base', 'banner_image'],
    title: 'Body_destinations-create_destination'
} as const;

export const Body_destinations_update_destinationSchema = {
    properties: {
        destination_base: {
            '$ref': '#/components/schemas/DestinationUpdateBase'
        },
        banner_image: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Banner Image'
        },
        side_image: {
            anyOf: [
                {
                    type: 'string',
                    format: 'binary'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Side Image'
        }
    },
    type: 'object',
    required: ['destination_base'],
    title: 'Body_destinations-update_destination'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CharterBaseSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Title'
        },
        description: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Description'
        },
        content1: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Content1'
        },
        content2: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content2'
        },
        content3: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content3'
        }
    },
    type: 'object',
    title: 'CharterBase'
} as const;

export const CharterImagePublicSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        alt_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alt Text'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        type: {
            '$ref': '#/components/schemas/CharterImageType'
        }
    },
    type: 'object',
    required: ['url', 'id', 'type'],
    title: 'CharterImagePublic'
} as const;

export const CharterImageTypeSchema = {
    type: 'string',
    enum: ['banner', 'block_1', 'block_2'],
    title: 'CharterImageType'
} as const;

export const CharterPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Title'
        },
        description: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Description'
        },
        content1: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Content1'
        },
        content2: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content2'
        },
        content3: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content3'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        banner_image: {
            '$ref': '#/components/schemas/CharterImagePublic'
        },
        block_1_image: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CharterImagePublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        block_2_image: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CharterImagePublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'owner_id', 'created_at', 'banner_image'],
    title: 'CharterPublic'
} as const;

export const CharterUpdateBaseSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        content1: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content1'
        },
        content2: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content2'
        },
        content3: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content3'
        }
    },
    type: 'object',
    required: ['title', 'description', 'content1'],
    title: 'CharterUpdateBase'
} as const;

export const ChartersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CharterPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ChartersPublic'
} as const;

export const CrewMemberBaseSchema = {
    properties: {
        first_name: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Last Name'
        },
        background: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Background'
        },
        role_id: {
            type: 'string',
            format: 'uuid',
            title: 'Role Id'
        },
        color: {
            type: 'string',
            maxLength: 7,
            minLength: 7,
            pattern: '^#[0-9A-Fa-f]{6}$',
            title: 'Color'
        },
        motto: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Motto'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        instagram: {
            type: 'string',
            maxLength: 30,
            minLength: 1,
            title: 'Instagram'
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'background', 'role_id', 'color', 'motto', 'email', 'instagram'],
    title: 'CrewMemberBase'
} as const;

export const CrewMemberDetailSchema = {
    properties: {
        member: {
            '$ref': '#/components/schemas/CrewMemberPublic'
        },
        navigation: {
            '$ref': '#/components/schemas/CrewMemberNavigation'
        }
    },
    type: 'object',
    required: ['member', 'navigation'],
    title: 'CrewMemberDetail'
} as const;

export const CrewMemberImagePublicSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        alt_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alt Text'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['url', 'id'],
    title: 'CrewMemberImagePublic'
} as const;

export const CrewMemberNavigationSchema = {
    properties: {
        previous: {
            type: 'string',
            format: 'uuid',
            title: 'Previous'
        },
        next: {
            type: 'string',
            format: 'uuid',
            title: 'Next'
        },
        position: {
            type: 'integer',
            title: 'Position'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['previous', 'next', 'position', 'total'],
    title: 'CrewMemberNavigation'
} as const;

export const CrewMemberPublicSchema = {
    properties: {
        first_name: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Last Name'
        },
        background: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Background'
        },
        role_id: {
            type: 'string',
            format: 'uuid',
            title: 'Role Id'
        },
        color: {
            type: 'string',
            maxLength: 7,
            minLength: 7,
            pattern: '^#[0-9A-Fa-f]{6}$',
            title: 'Color'
        },
        motto: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Motto'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        instagram: {
            type: 'string',
            maxLength: 30,
            minLength: 1,
            title: 'Instagram'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        role: {
            '$ref': '#/components/schemas/CrewMemberRolePublic'
        },
        image: {
            '$ref': '#/components/schemas/CrewMemberImagePublic'
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'background', 'role_id', 'color', 'motto', 'email', 'instagram', 'id', 'owner_id', 'created_at', 'role', 'image'],
    title: 'CrewMemberPublic'
} as const;

export const CrewMemberRoleCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CrewMemberRoleCreate'
} as const;

export const CrewMemberRolePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at', 'owner_id'],
    title: 'CrewMemberRolePublic'
} as const;

export const CrewMemberRoleUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'CrewMemberRoleUpdate'
} as const;

export const CrewMemberRolesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CrewMemberRolePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CrewMemberRolesPublic'
} as const;

export const CrewMemberUpdateBaseSchema = {
    properties: {
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        background: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Background'
        },
        role_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role Id'
        },
        color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 7,
                    minLength: 7,
                    pattern: '^#[0-9A-Fa-f]{6}$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        motto: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motto'
        },
        instagram: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 30,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Instagram'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'CrewMemberUpdateBase'
} as const;

export const CrewMembersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CrewMemberPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CrewMembersPublic'
} as const;

export const DestinationBaseSchema = {
    properties: {
        region: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Region'
        },
        country: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Country'
        },
        destination: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Destination'
        },
        description: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Description'
        },
        content1: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Content1'
        },
        content2: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content2'
        }
    },
    type: 'object',
    required: ['region', 'country', 'destination', 'description', 'content1'],
    title: 'DestinationBase'
} as const;

export const DestinationImagePublicSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        alt_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alt Text'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        type: {
            '$ref': '#/components/schemas/DestinationImageType'
        }
    },
    type: 'object',
    required: ['url', 'id', 'type'],
    title: 'DestinationImagePublic'
} as const;

export const DestinationImageTypeSchema = {
    type: 'string',
    enum: ['banner', 'side'],
    title: 'DestinationImageType'
} as const;

export const DestinationPublicSchema = {
    properties: {
        region: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Region'
        },
        country: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Country'
        },
        destination: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Destination'
        },
        description: {
            type: 'string',
            maxLength: 512,
            minLength: 1,
            title: 'Description'
        },
        content1: {
            type: 'string',
            maxLength: 1024,
            minLength: 1,
            title: 'Content1'
        },
        content2: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content2'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        banner_image: {
            '$ref': '#/components/schemas/DestinationImagePublic'
        },
        side_image: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DestinationImagePublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['region', 'country', 'destination', 'description', 'content1', 'id', 'owner_id', 'created_at', 'banner_image'],
    title: 'DestinationPublic'
} as const;

export const DestinationUpdateBaseSchema = {
    properties: {
        region: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        destination: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Destination'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        content1: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content1'
        },
        content2: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content2'
        }
    },
    type: 'object',
    title: 'DestinationUpdateBase'
} as const;

export const DestinationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DestinationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DestinationsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;