// This file is auto-generated by @hey-api/openapi-ts

export type Body_crew_members_create_crew_member = {
    crew_member_base: CrewMemberBase;
    image: (Blob | File);
};

export type Body_crew_members_update_crew_member = {
    crew_member_base: CrewMemberUpdateBase;
    image?: ((Blob | File) | null);
};

export type Body_destinations_create_destination = {
    destination_base: DestinationBase;
    banner_image: (Blob | File);
    side_image?: ((Blob | File) | null);
};

export type Body_destinations_update_destination = {
    destination_base: DestinationUpdateBase;
    banner_image?: ((Blob | File) | null);
    side_image?: ((Blob | File) | null);
};

export type Body_info_pages_create_info_page = {
    info_page_base: InfoPageBase;
    banner_image: (Blob | File);
    block_1_image?: ((Blob | File) | null);
    block_2_image?: ((Blob | File) | null);
};

export type Body_info_pages_update_info_page = {
    info_page_base: InfoPageUpdateBase;
    banner_image?: ((Blob | File) | null);
    block_1_image?: ((Blob | File) | null);
    block_2_image?: ((Blob | File) | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CrewMemberBase = {
    first_name: string;
    last_name: string;
    background: string;
    role_id: string;
    color: string;
    motto: string;
    email: string;
    instagram: string;
};

export type CrewMemberDetail = {
    member: CrewMemberPublic;
    navigation: CrewMemberNavigation;
};

export type CrewMemberImagePublic = {
    url: string;
    alt_text?: (string | null);
    id: string;
};

export type CrewMemberNavigation = {
    previous: string;
    next: string;
    position: number;
    total: number;
};

export type CrewMemberPublic = {
    first_name: string;
    last_name: string;
    background: string;
    role_id: string;
    color: string;
    motto: string;
    email: string;
    instagram: string;
    id: string;
    owner_id: string;
    created_at: string;
    role: CrewMemberRolePublic;
    image: CrewMemberImagePublic;
};

export type CrewMemberRoleCreate = {
    name: string;
};

export type CrewMemberRolePublic = {
    name: string;
    id: string;
    created_at: string;
    owner_id: string;
};

export type CrewMemberRolesPublic = {
    data: Array<CrewMemberRolePublic>;
    count: number;
};

export type CrewMemberRoleUpdate = {
    name?: (string | null);
};

export type CrewMembersPublic = {
    data: Array<CrewMemberPublic>;
    count: number;
};

export type CrewMemberUpdateBase = {
    first_name?: (string | null);
    last_name?: (string | null);
    background?: (string | null);
    role_id?: (string | null);
    color?: (string | null);
    motto?: (string | null);
    instagram?: (string | null);
    email?: (string | null);
};

export type DestinationBase = {
    region: string;
    country: string;
    destination: string;
    description: string;
    content1: string;
    content2?: (string | null);
};

export type DestinationImagePublic = {
    url: string;
    alt_text?: (string | null);
    id: string;
    type: DestinationImageType;
};

export type DestinationImageType = 'banner' | 'side';

export type DestinationPublic = {
    region: string;
    country: string;
    destination: string;
    description: string;
    content1: string;
    content2?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    banner_image: DestinationImagePublic;
    side_image?: (DestinationImagePublic | null);
};

export type DestinationsPublic = {
    data: Array<DestinationPublic>;
    count: number;
};

export type DestinationUpdateBase = {
    region?: (string | null);
    country?: (string | null);
    destination?: (string | null);
    description?: (string | null);
    content1?: (string | null);
    content2?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InfoPageBase = {
    title?: string;
    description?: string;
    content1?: string;
    content2?: (string | null);
    content3?: (string | null);
    services?: (InfoPageServiceList | null);
};

export type InfoPageImagePublic = {
    url: string;
    alt_text?: (string | null);
    id: string;
    type: InfoPageImageType;
};

export type InfoPageImageType = 'banner' | 'block_1' | 'block_2';

export type InfoPageMenuItemPublic = {
    id: string;
    created_at: string;
    owner_id: string;
    title: string;
};

export type InfoPageMenuItemsPublic = {
    data: Array<InfoPageMenuItemPublic>;
    count: number;
};

export type InfoPagePublic = {
    title?: string;
    description?: string;
    content1?: string;
    content2?: (string | null);
    content3?: (string | null);
    services?: (InfoPageServiceList | null);
    id: string;
    owner_id: string;
    created_at: string;
    banner_image: InfoPageImagePublic;
    block_1_image?: (InfoPageImagePublic | null);
    block_2_image?: (InfoPageImagePublic | null);
};

export type InfoPageServiceList = {
    title: string;
    content: string;
};

export type InfoPagesPublic = {
    data: Array<InfoPagePublic>;
    count: number;
};

export type InfoPageUpdateBase = {
    title?: (string | null);
    description?: (string | null);
    content1?: (string | null);
    content2?: (string | null);
    content3?: (string | null);
    services?: (InfoPageServiceList | null);
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type CrewMemberRolesReadCrewMemberRolesData = {
    limit?: number;
    skip?: number;
};

export type CrewMemberRolesReadCrewMemberRolesResponse = (CrewMemberRolesPublic);

export type CrewMemberRolesCreateCrewMemberRoleData = {
    requestBody: CrewMemberRoleCreate;
};

export type CrewMemberRolesCreateCrewMemberRoleResponse = (CrewMemberRolePublic);

export type CrewMemberRolesReadCrewMemberRoleData = {
    id: string;
};

export type CrewMemberRolesReadCrewMemberRoleResponse = (CrewMemberRolePublic);

export type CrewMemberRolesUpdateCrewMemberRoleData = {
    id: string;
    requestBody: CrewMemberRoleUpdate;
};

export type CrewMemberRolesUpdateCrewMemberRoleResponse = (CrewMemberRolePublic);

export type CrewMemberRolesDeleteCrewMemberRoleData = {
    id: string;
};

export type CrewMemberRolesDeleteCrewMemberRoleResponse = (Message);

export type CrewMembersReadCrewMembersData = {
    limit?: number;
    skip?: number;
};

export type CrewMembersReadCrewMembersResponse = (CrewMembersPublic);

export type CrewMembersCreateCrewMemberData = {
    formData: Body_crew_members_create_crew_member;
};

export type CrewMembersCreateCrewMemberResponse = (CrewMemberPublic);

export type CrewMembersReadCrewMemberData = {
    id: string;
};

export type CrewMembersReadCrewMemberResponse = (CrewMemberDetail);

export type CrewMembersUpdateCrewMemberData = {
    formData: Body_crew_members_update_crew_member;
    id: string;
};

export type CrewMembersUpdateCrewMemberResponse = (CrewMemberPublic);

export type CrewMembersDeleteCrewMemberData = {
    id: string;
};

export type CrewMembersDeleteCrewMemberResponse = (Message);

export type DestinationsReadDestinationsData = {
    limit?: number;
    skip?: number;
};

export type DestinationsReadDestinationsResponse = (DestinationsPublic);

export type DestinationsCreateDestinationData = {
    formData: Body_destinations_create_destination;
};

export type DestinationsCreateDestinationResponse = (DestinationPublic);

export type DestinationsReadDestinationData = {
    id: string;
};

export type DestinationsReadDestinationResponse = (DestinationPublic);

export type DestinationsUpdateDestinationData = {
    formData: Body_destinations_update_destination;
    id: string;
};

export type DestinationsUpdateDestinationResponse = (DestinationPublic);

export type DestinationsDeleteDestinationData = {
    id: string;
};

export type DestinationsDeleteDestinationResponse = (Message);

export type InfoPagesReadInfoPagesData = {
    limit?: number;
    skip?: number;
};

export type InfoPagesReadInfoPagesResponse = (InfoPagesPublic);

export type InfoPagesCreateInfoPageData = {
    formData: Body_info_pages_create_info_page;
};

export type InfoPagesCreateInfoPageResponse = (InfoPagePublic);

export type InfoPagesReadInfoPageMenuItemsData = {
    limit?: number;
    skip?: number;
};

export type InfoPagesReadInfoPageMenuItemsResponse = (InfoPageMenuItemsPublic);

export type InfoPagesReadInfoPageData = {
    id: string;
};

export type InfoPagesReadInfoPageResponse = (InfoPagePublic);

export type InfoPagesUpdateInfoPageData = {
    formData: Body_info_pages_update_info_page;
    id: string;
};

export type InfoPagesUpdateInfoPageResponse = (InfoPagePublic);

export type InfoPagesDeleteInfoPageData = {
    id: string;
};

export type InfoPagesDeleteInfoPageResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);