"""increase background limit for CrewMember

Revision ID: 6d23f0539730
Revises: 9b7089a7c60a
Create Date: 2026-08-06 04:56:41.532386

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6d23f0539730'
down_revision = '9b7089a7c60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crew_member', 'background',
               existing_type=sa.VARCHAR(length=512),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crew_member', 'background',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###
