"""add destination

Revision ID: 6fd9276d868d
Revises: f43fc4f06280
Create Date: 2026-07-02 22:09:57.870473

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6fd9276d868d'
down_revision = 'f43fc4f06280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('destination', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('content1', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('content2', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destination_destination'), 'destination', ['destination'], unique=True)
    op.create_table('destination_image',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('banner', 'side', name='destinationimagetype'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'type', name='uq_destination_image_type')
    )
    op.create_index(op.f('ix_destination_image_type'), 'destination_image', ['type'], unique=False)
    op.alter_column('crew_member', 'motto',
               existing_type=sa.VARCHAR(length=510),
               type_=sqlmodel.sql.sqltypes.AutoString(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crew_member', 'motto',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=512),
               type_=sa.VARCHAR(length=510),
               existing_nullable=False)
    op.drop_index(op.f('ix_destination_image_type'), table_name='destination_image')
    op.drop_table('destination_image')
    op.drop_index(op.f('ix_destination_destination'), table_name='destination')
    op.drop_table('destination')
    # ### end Alembic commands ###
