"""add order to CrewMember

Revision ID: 9b7089a7c60a
Revises: 6fd9276d868d
Create Date: 2026-07-25 16:20:12.136054

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9b7089a7c60a'
down_revision = '6fd9276d868d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_member', sa.Column('order', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_crew_member_order'), 'crew_member', ['order'], unique=True)
    op.drop_constraint(op.f('destination_image_destination_id_fkey'), 'destination_image', type_='foreignkey')
    op.create_foreign_key(None, 'destination_image', 'destination', ['destination_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'destination_image', type_='foreignkey')
    op.create_foreign_key(op.f('destination_image_destination_id_fkey'), 'destination_image', 'destination', ['destination_id'], ['id'])
    op.drop_index(op.f('ix_crew_member_order'), table_name='crew_member')
    op.drop_column('crew_member', 'order')
    # ### end Alembic commands ###
