"""add InfoPages

Revision ID: a321b78183e7
Revises: 6d23f0539730
Create Date: 2026-08-16 16:51:17.360176

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a321b78183e7'
down_revision = '6d23f0539730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_page',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('content1', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('content2', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('content3', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_page_title'), 'info_page', ['title'], unique=True)
    op.create_table('info_page_image',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('info_page_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('banner', 'block_1', 'block_2', name='infopageimagetype'), nullable=False),
    sa.ForeignKeyConstraint(['info_page_id'], ['info_page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('info_page_id', 'type', name='uq_info_page_image_type')
    )
    op.create_index(op.f('ix_info_page_image_type'), 'info_page_image', ['type'], unique=False)
    op.drop_constraint(op.f('crew_member_image_crew_member_id_fkey'), 'crew_member_image', type_='foreignkey')
    op.create_foreign_key(None, 'crew_member_image', 'crew_member', ['crew_member_id'], ['id'], ondelete='CASCADE')
    op.alter_column('destination', 'content1',
               existing_type=sa.VARCHAR(length=1024),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2048),
               existing_nullable=False)
    op.alter_column('destination', 'content2',
               existing_type=sa.VARCHAR(length=1024),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('destination', 'content2',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2048),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('destination', 'content1',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2048),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.drop_constraint(op.f('crew_member_image_crew_member_id_fkey'), 'crew_member_image', type_='foreignkey')
    op.create_foreign_key(op.f('crew_member_image_crew_member_id_fkey'), 'crew_member_image', 'crew_member', ['crew_member_id'], ['id'])
    op.drop_index(op.f('ix_info_page_image_type'), table_name='info_page_image')
    op.drop_table('info_page_image')
    op.drop_index(op.f('ix_info_page_title'), table_name='info_page')
    op.drop_table('info_page')
    # ### end Alembic commands ###
