"""add optional service list to InfoPage

Revision ID: c2cdcd664b9d
Revises: a321b78183e7
Create Date: 2026-08-23 20:42:32.987180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2cdcd664b9d'
down_revision = 'a321b78183e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info_page', sa.Column('services', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_page', 'services')
    # ### end Alembic commands ###
