"""add CrewMemberRole & CrewMember

Revision ID: e38fdc4e2d2a
Revises: fe56fa70289e
Create Date: 2026-06-14 21:27:13.682179

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e38fdc4e2d2a'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crew_member_role',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crew_member',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('motto', sqlmodel.sql.sqltypes.AutoString(length=510), nullable=False),
    sa.Column('instagram', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['crew_member_role.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crew_member_email'), 'crew_member', ['email'], unique=True)
    op.create_index(op.f('ix_crew_member_instagram'), 'crew_member', ['instagram'], unique=True)
    op.create_index(op.f('ix_crew_member_role_id'), 'crew_member', ['role_id'], unique=False)
    op.create_table('crew_member_image',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('crew_member_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['crew_member_id'], ['crew_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crew_member_image')
    op.drop_index(op.f('ix_crew_member_role_id'), table_name='crew_member')
    op.drop_index(op.f('ix_crew_member_instagram'), table_name='crew_member')
    op.drop_index(op.f('ix_crew_member_email'), table_name='crew_member')
    op.drop_table('crew_member')
    op.drop_table('crew_member_role')
    # ### end Alembic commands ###
