"""add CrewMember

Revision ID: f43fc4f06280
Revises: e38fdc4e2d2a
Create Date: 2026-06-20 17:58:54.608409

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f43fc4f06280'
down_revision = 'e38fdc4e2d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_member', sa.Column('background', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crew_member', 'background')
    # ### end Alembic commands ###
