/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Main_layoutRouteImport } from './routes/_main_layout'
import { Route as Admin_layoutRouteImport } from './routes/_admin_layout'
import { Route as Main_layoutIndexRouteImport } from './routes/_main_layout/index'
import { Route as Main_layoutAboutRouteImport } from './routes/_main_layout/about'
import { Route as Main_layoutMembersIndexRouteImport } from './routes/_main_layout/members/index'
import { Route as Main_layoutDestinationsIndexRouteImport } from './routes/_main_layout/destinations/index'
import { Route as Admin_layoutAdminIndexRouteImport } from './routes/_admin_layout/admin/index'
import { Route as Main_layoutMembersIdRouteImport } from './routes/_main_layout/members/$id'
import { Route as Main_layoutDestinationsIdRouteImport } from './routes/_main_layout/destinations/$id'
import { Route as Admin_layoutAdminSettingsRouteImport } from './routes/_admin_layout/admin/settings'
import { Route as Admin_layoutAdminItemsRouteImport } from './routes/_admin_layout/admin/items'
import { Route as Admin_layoutAdminCrewMembersRouteImport } from './routes/_admin_layout/admin/crew-members'
import { Route as Admin_layoutAdminCrewMemberRolesRouteImport } from './routes/_admin_layout/admin/crew-member-roles'
import { Route as Admin_layoutAdminAdminManagementRouteImport } from './routes/_admin_layout/admin/admin-management'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Main_layoutRoute = Main_layoutRouteImport.update({
  id: '/_main_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_layoutRoute = Admin_layoutRouteImport.update({
  id: '/_admin_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const Main_layoutIndexRoute = Main_layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Main_layoutRoute,
} as any)
const Main_layoutAboutRoute = Main_layoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => Main_layoutRoute,
} as any)
const Main_layoutMembersIndexRoute = Main_layoutMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => Main_layoutRoute,
} as any)
const Main_layoutDestinationsIndexRoute =
  Main_layoutDestinationsIndexRouteImport.update({
    id: '/destinations/',
    path: '/destinations/',
    getParentRoute: () => Main_layoutRoute,
  } as any)
const Admin_layoutAdminIndexRoute = Admin_layoutAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => Admin_layoutRoute,
} as any)
const Main_layoutMembersIdRoute = Main_layoutMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => Main_layoutRoute,
} as any)
const Main_layoutDestinationsIdRoute =
  Main_layoutDestinationsIdRouteImport.update({
    id: '/destinations/$id',
    path: '/destinations/$id',
    getParentRoute: () => Main_layoutRoute,
  } as any)
const Admin_layoutAdminSettingsRoute =
  Admin_layoutAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => Admin_layoutRoute,
  } as any)
const Admin_layoutAdminItemsRoute = Admin_layoutAdminItemsRouteImport.update({
  id: '/admin/items',
  path: '/admin/items',
  getParentRoute: () => Admin_layoutRoute,
} as any)
const Admin_layoutAdminCrewMembersRoute =
  Admin_layoutAdminCrewMembersRouteImport.update({
    id: '/admin/crew-members',
    path: '/admin/crew-members',
    getParentRoute: () => Admin_layoutRoute,
  } as any)
const Admin_layoutAdminCrewMemberRolesRoute =
  Admin_layoutAdminCrewMemberRolesRouteImport.update({
    id: '/admin/crew-member-roles',
    path: '/admin/crew-member-roles',
    getParentRoute: () => Admin_layoutRoute,
  } as any)
const Admin_layoutAdminAdminManagementRoute =
  Admin_layoutAdminAdminManagementRouteImport.update({
    id: '/admin/admin-management',
    path: '/admin/admin-management',
    getParentRoute: () => Admin_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof Main_layoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/about': typeof Main_layoutAboutRoute
  '/admin/admin-management': typeof Admin_layoutAdminAdminManagementRoute
  '/admin/crew-member-roles': typeof Admin_layoutAdminCrewMemberRolesRoute
  '/admin/crew-members': typeof Admin_layoutAdminCrewMembersRoute
  '/admin/items': typeof Admin_layoutAdminItemsRoute
  '/admin/settings': typeof Admin_layoutAdminSettingsRoute
  '/destinations/$id': typeof Main_layoutDestinationsIdRoute
  '/members/$id': typeof Main_layoutMembersIdRoute
  '/admin/': typeof Admin_layoutAdminIndexRoute
  '/destinations/': typeof Main_layoutDestinationsIndexRoute
  '/members/': typeof Main_layoutMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof Main_layoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/about': typeof Main_layoutAboutRoute
  '/admin/admin-management': typeof Admin_layoutAdminAdminManagementRoute
  '/admin/crew-member-roles': typeof Admin_layoutAdminCrewMemberRolesRoute
  '/admin/crew-members': typeof Admin_layoutAdminCrewMembersRoute
  '/admin/items': typeof Admin_layoutAdminItemsRoute
  '/admin/settings': typeof Admin_layoutAdminSettingsRoute
  '/destinations/$id': typeof Main_layoutDestinationsIdRoute
  '/members/$id': typeof Main_layoutMembersIdRoute
  '/admin': typeof Admin_layoutAdminIndexRoute
  '/destinations': typeof Main_layoutDestinationsIndexRoute
  '/members': typeof Main_layoutMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin_layout': typeof Admin_layoutRouteWithChildren
  '/_main_layout': typeof Main_layoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_main_layout/about': typeof Main_layoutAboutRoute
  '/_main_layout/': typeof Main_layoutIndexRoute
  '/_admin_layout/admin/admin-management': typeof Admin_layoutAdminAdminManagementRoute
  '/_admin_layout/admin/crew-member-roles': typeof Admin_layoutAdminCrewMemberRolesRoute
  '/_admin_layout/admin/crew-members': typeof Admin_layoutAdminCrewMembersRoute
  '/_admin_layout/admin/items': typeof Admin_layoutAdminItemsRoute
  '/_admin_layout/admin/settings': typeof Admin_layoutAdminSettingsRoute
  '/_main_layout/destinations/$id': typeof Main_layoutDestinationsIdRoute
  '/_main_layout/members/$id': typeof Main_layoutMembersIdRoute
  '/_admin_layout/admin/': typeof Admin_layoutAdminIndexRoute
  '/_main_layout/destinations/': typeof Main_layoutDestinationsIndexRoute
  '/_main_layout/members/': typeof Main_layoutMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/about'
    | '/admin/admin-management'
    | '/admin/crew-member-roles'
    | '/admin/crew-members'
    | '/admin/items'
    | '/admin/settings'
    | '/destinations/$id'
    | '/members/$id'
    | '/admin/'
    | '/destinations/'
    | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/about'
    | '/admin/admin-management'
    | '/admin/crew-member-roles'
    | '/admin/crew-members'
    | '/admin/items'
    | '/admin/settings'
    | '/destinations/$id'
    | '/members/$id'
    | '/admin'
    | '/destinations'
    | '/members'
  id:
    | '__root__'
    | '/_admin_layout'
    | '/_main_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_main_layout/about'
    | '/_main_layout/'
    | '/_admin_layout/admin/admin-management'
    | '/_admin_layout/admin/crew-member-roles'
    | '/_admin_layout/admin/crew-members'
    | '/_admin_layout/admin/items'
    | '/_admin_layout/admin/settings'
    | '/_main_layout/destinations/$id'
    | '/_main_layout/members/$id'
    | '/_admin_layout/admin/'
    | '/_main_layout/destinations/'
    | '/_main_layout/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Admin_layoutRoute: typeof Admin_layoutRouteWithChildren
  Main_layoutRoute: typeof Main_layoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main_layout': {
      id: '/_main_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Main_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin_layout': {
      id: '/_admin_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Admin_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main_layout/': {
      id: '/_main_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Main_layoutIndexRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/_main_layout/about': {
      id: '/_main_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof Main_layoutAboutRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/_main_layout/members/': {
      id: '/_main_layout/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof Main_layoutMembersIndexRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/_main_layout/destinations/': {
      id: '/_main_layout/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof Main_layoutDestinationsIndexRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/_admin_layout/admin/': {
      id: '/_admin_layout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof Admin_layoutAdminIndexRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
    '/_main_layout/members/$id': {
      id: '/_main_layout/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof Main_layoutMembersIdRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/_main_layout/destinations/$id': {
      id: '/_main_layout/destinations/$id'
      path: '/destinations/$id'
      fullPath: '/destinations/$id'
      preLoaderRoute: typeof Main_layoutDestinationsIdRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/_admin_layout/admin/settings': {
      id: '/_admin_layout/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof Admin_layoutAdminSettingsRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
    '/_admin_layout/admin/items': {
      id: '/_admin_layout/admin/items'
      path: '/admin/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof Admin_layoutAdminItemsRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
    '/_admin_layout/admin/crew-members': {
      id: '/_admin_layout/admin/crew-members'
      path: '/admin/crew-members'
      fullPath: '/admin/crew-members'
      preLoaderRoute: typeof Admin_layoutAdminCrewMembersRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
    '/_admin_layout/admin/crew-member-roles': {
      id: '/_admin_layout/admin/crew-member-roles'
      path: '/admin/crew-member-roles'
      fullPath: '/admin/crew-member-roles'
      preLoaderRoute: typeof Admin_layoutAdminCrewMemberRolesRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
    '/_admin_layout/admin/admin-management': {
      id: '/_admin_layout/admin/admin-management'
      path: '/admin/admin-management'
      fullPath: '/admin/admin-management'
      preLoaderRoute: typeof Admin_layoutAdminAdminManagementRouteImport
      parentRoute: typeof Admin_layoutRoute
    }
  }
}

interface Admin_layoutRouteChildren {
  Admin_layoutAdminAdminManagementRoute: typeof Admin_layoutAdminAdminManagementRoute
  Admin_layoutAdminCrewMemberRolesRoute: typeof Admin_layoutAdminCrewMemberRolesRoute
  Admin_layoutAdminCrewMembersRoute: typeof Admin_layoutAdminCrewMembersRoute
  Admin_layoutAdminItemsRoute: typeof Admin_layoutAdminItemsRoute
  Admin_layoutAdminSettingsRoute: typeof Admin_layoutAdminSettingsRoute
  Admin_layoutAdminIndexRoute: typeof Admin_layoutAdminIndexRoute
}

const Admin_layoutRouteChildren: Admin_layoutRouteChildren = {
  Admin_layoutAdminAdminManagementRoute: Admin_layoutAdminAdminManagementRoute,
  Admin_layoutAdminCrewMemberRolesRoute: Admin_layoutAdminCrewMemberRolesRoute,
  Admin_layoutAdminCrewMembersRoute: Admin_layoutAdminCrewMembersRoute,
  Admin_layoutAdminItemsRoute: Admin_layoutAdminItemsRoute,
  Admin_layoutAdminSettingsRoute: Admin_layoutAdminSettingsRoute,
  Admin_layoutAdminIndexRoute: Admin_layoutAdminIndexRoute,
}

const Admin_layoutRouteWithChildren = Admin_layoutRoute._addFileChildren(
  Admin_layoutRouteChildren,
)

interface Main_layoutRouteChildren {
  Main_layoutAboutRoute: typeof Main_layoutAboutRoute
  Main_layoutIndexRoute: typeof Main_layoutIndexRoute
  Main_layoutDestinationsIdRoute: typeof Main_layoutDestinationsIdRoute
  Main_layoutMembersIdRoute: typeof Main_layoutMembersIdRoute
  Main_layoutDestinationsIndexRoute: typeof Main_layoutDestinationsIndexRoute
  Main_layoutMembersIndexRoute: typeof Main_layoutMembersIndexRoute
}

const Main_layoutRouteChildren: Main_layoutRouteChildren = {
  Main_layoutAboutRoute: Main_layoutAboutRoute,
  Main_layoutIndexRoute: Main_layoutIndexRoute,
  Main_layoutDestinationsIdRoute: Main_layoutDestinationsIdRoute,
  Main_layoutMembersIdRoute: Main_layoutMembersIdRoute,
  Main_layoutDestinationsIndexRoute: Main_layoutDestinationsIndexRoute,
  Main_layoutMembersIndexRoute: Main_layoutMembersIndexRoute,
}

const Main_layoutRouteWithChildren = Main_layoutRoute._addFileChildren(
  Main_layoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  Admin_layoutRoute: Admin_layoutRouteWithChildren,
  Main_layoutRoute: Main_layoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
