/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Main_layoutRouteImport } from './routes/_main_layout'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as Main_layoutIndexRouteImport } from './routes/_main_layout/index'
import { Route as LayoutCrewMemberRoleRouteImport } from './routes/_layout/crew-member-role'
import { Route as Main_layoutMembersIndexRouteImport } from './routes/_main_layout/members/index'
import { Route as Main_layoutDestinationsIndexRouteImport } from './routes/_main_layout/destinations/index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as Main_layoutMembersSlugRouteImport } from './routes/_main_layout/members/$slug'
import { Route as Main_layoutDestinationsSlugRouteImport } from './routes/_main_layout/destinations/$slug'
import { Route as LayoutAdminSettingsRouteImport } from './routes/_layout/admin/settings'
import { Route as LayoutAdminItemsRouteImport } from './routes/_layout/admin/items'
import { Route as LayoutAdminAdminRouteImport } from './routes/_layout/admin/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Main_layoutRoute = Main_layoutRouteImport.update({
  id: '/_main_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const Main_layoutIndexRoute = Main_layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Main_layoutRoute,
} as any)
const LayoutCrewMemberRoleRoute = LayoutCrewMemberRoleRouteImport.update({
  id: '/crew-member-role',
  path: '/crew-member-role',
  getParentRoute: () => LayoutRoute,
} as any)
const Main_layoutMembersIndexRoute = Main_layoutMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => Main_layoutRoute,
} as any)
const Main_layoutDestinationsIndexRoute =
  Main_layoutDestinationsIndexRouteImport.update({
    id: '/destinations/',
    path: '/destinations/',
    getParentRoute: () => Main_layoutRoute,
  } as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LayoutRoute,
} as any)
const Main_layoutMembersSlugRoute = Main_layoutMembersSlugRouteImport.update({
  id: '/members/$slug',
  path: '/members/$slug',
  getParentRoute: () => Main_layoutRoute,
} as any)
const Main_layoutDestinationsSlugRoute =
  Main_layoutDestinationsSlugRouteImport.update({
    id: '/destinations/$slug',
    path: '/destinations/$slug',
    getParentRoute: () => Main_layoutRoute,
  } as any)
const LayoutAdminSettingsRoute = LayoutAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminItemsRoute = LayoutAdminItemsRouteImport.update({
  id: '/admin/items',
  path: '/admin/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminAdminRoute = LayoutAdminAdminRouteImport.update({
  id: '/admin/admin',
  path: '/admin/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof Main_layoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/crew-member-role': typeof LayoutCrewMemberRoleRoute
  '/admin/admin': typeof LayoutAdminAdminRoute
  '/admin/items': typeof LayoutAdminItemsRoute
  '/admin/settings': typeof LayoutAdminSettingsRoute
  '/destinations/$slug': typeof Main_layoutDestinationsSlugRoute
  '/members/$slug': typeof Main_layoutMembersSlugRoute
  '/admin/': typeof LayoutAdminIndexRoute
  '/destinations/': typeof Main_layoutDestinationsIndexRoute
  '/members/': typeof Main_layoutMembersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof Main_layoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/crew-member-role': typeof LayoutCrewMemberRoleRoute
  '/admin/admin': typeof LayoutAdminAdminRoute
  '/admin/items': typeof LayoutAdminItemsRoute
  '/admin/settings': typeof LayoutAdminSettingsRoute
  '/destinations/$slug': typeof Main_layoutDestinationsSlugRoute
  '/members/$slug': typeof Main_layoutMembersSlugRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/destinations': typeof Main_layoutDestinationsIndexRoute
  '/members': typeof Main_layoutMembersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_main_layout': typeof Main_layoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/crew-member-role': typeof LayoutCrewMemberRoleRoute
  '/_main_layout/': typeof Main_layoutIndexRoute
  '/_layout/admin/admin': typeof LayoutAdminAdminRoute
  '/_layout/admin/items': typeof LayoutAdminItemsRoute
  '/_layout/admin/settings': typeof LayoutAdminSettingsRoute
  '/_main_layout/destinations/$slug': typeof Main_layoutDestinationsSlugRoute
  '/_main_layout/members/$slug': typeof Main_layoutMembersSlugRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_main_layout/destinations/': typeof Main_layoutDestinationsIndexRoute
  '/_main_layout/members/': typeof Main_layoutMembersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/crew-member-role'
    | '/admin/admin'
    | '/admin/items'
    | '/admin/settings'
    | '/destinations/$slug'
    | '/members/$slug'
    | '/admin/'
    | '/destinations/'
    | '/members/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/crew-member-role'
    | '/admin/admin'
    | '/admin/items'
    | '/admin/settings'
    | '/destinations/$slug'
    | '/members/$slug'
    | '/admin'
    | '/destinations'
    | '/members'
  id:
    | '__root__'
    | '/_layout'
    | '/_main_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/crew-member-role'
    | '/_main_layout/'
    | '/_layout/admin/admin'
    | '/_layout/admin/items'
    | '/_layout/admin/settings'
    | '/_main_layout/destinations/$slug'
    | '/_main_layout/members/$slug'
    | '/_layout/admin/'
    | '/_main_layout/destinations/'
    | '/_main_layout/members/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  Main_layoutRoute: typeof Main_layoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main_layout': {
      id: '/_main_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Main_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main_layout/': {
      id: '/_main_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof Main_layoutIndexRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/_layout/crew-member-role': {
      id: '/_layout/crew-member-role'
      path: '/crew-member-role'
      fullPath: '/crew-member-role'
      preLoaderRoute: typeof LayoutCrewMemberRoleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_main_layout/members/': {
      id: '/_main_layout/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof Main_layoutMembersIndexRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/_main_layout/destinations/': {
      id: '/_main_layout/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof Main_layoutDestinationsIndexRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_main_layout/members/$slug': {
      id: '/_main_layout/members/$slug'
      path: '/members/$slug'
      fullPath: '/members/$slug'
      preLoaderRoute: typeof Main_layoutMembersSlugRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/_main_layout/destinations/$slug': {
      id: '/_main_layout/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof Main_layoutDestinationsSlugRouteImport
      parentRoute: typeof Main_layoutRoute
    }
    '/_layout/admin/settings': {
      id: '/_layout/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof LayoutAdminSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/items': {
      id: '/_layout/admin/items'
      path: '/admin/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof LayoutAdminItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/admin': {
      id: '/_layout/admin/admin'
      path: '/admin/admin'
      fullPath: '/admin/admin'
      preLoaderRoute: typeof LayoutAdminAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCrewMemberRoleRoute: typeof LayoutCrewMemberRoleRoute
  LayoutAdminAdminRoute: typeof LayoutAdminAdminRoute
  LayoutAdminItemsRoute: typeof LayoutAdminItemsRoute
  LayoutAdminSettingsRoute: typeof LayoutAdminSettingsRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCrewMemberRoleRoute: LayoutCrewMemberRoleRoute,
  LayoutAdminAdminRoute: LayoutAdminAdminRoute,
  LayoutAdminItemsRoute: LayoutAdminItemsRoute,
  LayoutAdminSettingsRoute: LayoutAdminSettingsRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface Main_layoutRouteChildren {
  Main_layoutIndexRoute: typeof Main_layoutIndexRoute
  Main_layoutDestinationsSlugRoute: typeof Main_layoutDestinationsSlugRoute
  Main_layoutMembersSlugRoute: typeof Main_layoutMembersSlugRoute
  Main_layoutDestinationsIndexRoute: typeof Main_layoutDestinationsIndexRoute
  Main_layoutMembersIndexRoute: typeof Main_layoutMembersIndexRoute
}

const Main_layoutRouteChildren: Main_layoutRouteChildren = {
  Main_layoutIndexRoute: Main_layoutIndexRoute,
  Main_layoutDestinationsSlugRoute: Main_layoutDestinationsSlugRoute,
  Main_layoutMembersSlugRoute: Main_layoutMembersSlugRoute,
  Main_layoutDestinationsIndexRoute: Main_layoutDestinationsIndexRoute,
  Main_layoutMembersIndexRoute: Main_layoutMembersIndexRoute,
}

const Main_layoutRouteWithChildren = Main_layoutRoute._addFileChildren(
  Main_layoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  Main_layoutRoute: Main_layoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
